# Generated by Django 2.0.2 on 2018-09-12 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixActif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(help_text="entrer le nom de l'entreprise", max_length=20)),
                ('decription_entreprise', models.TextField(help_text='entrer une description', max_length=1000)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
            options={
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Entrer un commentaire', max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, help_text='Entrer la date du début de la simulation', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Entrer la date de fin de la simulation', null=True)),
                ('imagefirst', models.ImageField(upload_to='first')),
                ('imagesecond', models.ImageField(upload_to='second')),
                ('actifs', models.ManyToManyField(help_text='Choisir un actif', to='simulation.ChoixActif')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.Simulation'),
        ),
    ]
