# Generated by Django 2.0.2 on 2018-09-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(help_text="entrer le nom de l'activité", max_length=20)),
                ('description_activite', models.TextField(help_text="entrer une description de l'activité", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(help_text="entrer le nom de l'entreprise", max_length=20)),
                ('description_entreprise', models.TextField(help_text="entrer une description de l'éntreprise", max_length=1000)),
            ],
            options={
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='actifs',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='simulation',
        ),
        migrations.DeleteModel(
            name='ChoixActif',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.Activite'),
        ),
    ]
